spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # \u6307\u5B9A\u5F53profile=peer1\u65F6\uFF0C\u4E3B\u673A\u540D\u662Fpeer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/ # \u5C06\u81EA\u5DF1\u6CE8\u518C\u5230peer2\u8FD9\u4E2AEureka\u4E0A\u9762\u53BB

---

spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/