server:
  port: 8011
eureka:
  client:
    service-url:
      # \u6307\u5B9Aeureka server\u901A\u4FE1\u5730\u5740\uFF0C\u6CE8\u610F/eureka/\u5C0F\u5C3E\u5DF4\u4E0D\u80FD\u5C11
      defaultZone: http://localhost:8761/eureka/
  instance:
    # \u662F\u5426\u6CE8\u518CIP\u5230eureka server,\u5982\u4E0D\u6307\u5B9A\u6216\u8BBE\u7F6E\u4E3Afalse\uFF0C\u90A3\u5C31\u4F1A\u6CE8\u518C\u4E3B\u673A\u540D
    prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics
spring:
  application:
    # \u6307\u5B9A\u6CE8\u518C\u5230eureka server\u4E0A\u7684\u670D\u52A1\u540D\u79F0\uFF0C
    name: consumer-movie
logging:
  level:
    com.learn.simpleconsumermoviefeign.feignclient: debug
# 在feign中启用hystrix
feign:
  hystrix:
    enabled: true